### ISSUE TITLE
Event persisted? method prone to bugs

### ISSUE THREAD

**Issue by patpaev** [envato/event_sourcery#180]
The `EventSourcery::Event` `persisted?` method is just a [simple check](https://github.com/envato/event_sourcery/blob/c6aebbb232d649ab9edb9e4c5d204e66d02b756d/lib/event_sourcery/event.rb#L74-L76) of whether an ID is present.

However it's [documented](https://github.com/envato/event_sourcery/blob/c6aebbb232d649ab9edb9e4c5d204e66d02b756d/lib/event_sourcery/event.rb#L45) that you can pass an ID through as a param when initializing the class. 

This means that Events could erroneously respond `true` to `persisted?` if you've passed an `id` parameter whether it's been written to the database or not.

**Comment by andyjdavis** [comment]
This issue has now been resolved by removing the potentially misleading persisted? method. This change is available in 1.0.0 of the event_sourcery gem.
